name: Build

on:
  workflow_call:
    secrets:
      REPO_TOKEN:
        required: true
    inputs:
      REPO_LOGIN:
        required: true
        type: string
      REPO_IMAGE:
        required: true
        type: string
      VERSION:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ inputs.REPO_LOGIN }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.REPO_IMAGE }}
            ${{ github.repository }}
          labels: |
            org.opencontainers.image.version=${{ inputs.VERSION }}
            org.opencontainers.image.ref.name=${{ inputs.REPO_IMAGE }}:${{ inputs.VERSION }}

      - name: Build container images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            "version=${{ inputs.VERSION }}"
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ inputs.REPO_IMAGE }}:${{ inputs.VERSION }}
            ${{ inputs.REPO_IMAGE }}:latest
