name: Tests

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        continue-on-error: true
        with:
          version: latest
          args: --timeout 5m --verbose

      - name: Unit tests
        run: go test -v ./...

  linting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        continue-on-error: true
        with:
          version: latest
          args: --timeout 5m --verbose
